version: "3.8"
services:

  postgis:
    image: "mdillon/postgis"
    hostname: postgis
    ports:
      - "5432:5432"
    volumes:
      - /workspaces/geoserver-osm-styled/postgres_data/data:/var/lib/postgresql/data
  geoserver:
    image: "kartoza/geoserver"
    ports:
      - "8080:8080"
    volumes:
      - /workspaces/geoserver-osm-styled/osm-styles:/opt/geoserver/data_dir
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - GEOSERVER_DATA_DIR=/workspaces/geoserver-osm-styled/osm-styles
      - STABLE_EXTENSIONS=css-plugin,feature-pregeneralized-plugin
      - HTTP_PROXY_NAME=${CODESPACE_NAME}-8080.preview.app.github.dev
      - HTTP_SCHEME=https
      - MAXIMUM_MEMORY=756M
      - INITIAL_MEMORY=128M

networks:
  default:
    name: gist604b

