version: "3.8"
services:

  postgis:
    image: "mdillon/postgis"
    hostname: postgis
    ports:
      - "5432:5432"
    volumes:
      - /workspaces/geoserver-osm-styled/postgres_data/data:/var/lib/postgresql/data
  geoserver:
    image: "kartoza/geoserver"
    ports:
      - "8080:8080"
    volumes:
      - /workspaces/geoserver-osm-styled/osm-styles:/opt/geoserver/data_dir
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - STABLE_EXTENSIONS=css-plugin,feature-pregeneralized-plugin

networks:
  default:
    name: gist604b

